double r, height;
    cout << "Input the radius of the sphere:";
    cin >> r; 
    cout << "Input the radius and height of the cylinder:";
    cylinder c(height, r);
    cout << "Input the radius and height of the cone:";
    cin >> r >> height;
    cone cc(height ,r);
    c.show_area();
    c.show_vol();
    cc.show_area();
    cc.show_vol();