import time
from selenium.webdriver.common.by import By
from selenium import webdriver

username = '1668597'
password = '635695606lzx'

driver = webdriver.Chrome()
driver.get('http://ehall.cqupt.edu.cn/publicapp/sys/cyxsjkdkmobile/*default/index.html#/xs/index?userId=1668597&roleId=20220428150137410')

# driver.find_element(By.XPATH, '//*[@id="username"]').send_keys(username)
# driver.find_element(By.XPATH, '//*[@id="password"]').send_keys(password)
# driver.find_element(By.XPATH, '//*[@id="login_submit"]').click()
time.sleep(4)
driver.find_element(By.XPATH, '/html/body/div/div/div[2]/form/div[1]/div[4]/div[1]').click()
time.sleep(0.3)
driver.find_element(By.XPATH, '/html/body/div/div/div[2]/form/div[1]/div[6]/div/div[2]/div[3]/ul/li[8]').click()
time.sleep(0.3)
driver.find_element(By.XPATH, '/html/body/div/div/div[2]/form/div[1]/div[6]/div/div[1]/button[2]').click()
time.sleep(0.3)
driver.find_element(By.XPATH, '/html/body/div/div/div[2]/form/div[1]/div[7]/div[2]/div/textarea').send_keys('重庆邮电大学')
time.sleep(0.3)
driver.find_element(By.XPATH, '/html/body/div/div/div[2]/form/div[1]/div[8]/div[2]/div/input').click()
time.sleep(0.3)
driver.find_element(By.XPATH, '/html/body/div/div/div[2]/form/div[1]/div[10]/div/div[2]/div[1]/ul/li[3]').click()
time.sleep(0.3)
driver.find_element(By.XPATH, '/html/body/div/div/div[2]/form/div[1]/div[10]/div/div[1]/button[2]').click()
time.sleep(0.3)
driver.find_element(By.XPATH, '/html/body/div/div/div[2]/form/div[1]/div[11]/div[2]/div/input').click()
time.sleep(0.3)
driver.find_element(By.XPATH, '/html/body/div/div/div[2]/form/div[1]/div[13]/div/div[2]/div[1]/ul/li[3]').click()
time.sleep(0.3)
driver.find_element(By.XPATH, '/html/body/div/div/div[2]/form/div[1]/div[13]/div/div[1]/button[2]').click()
time.sleep(0.3)
driver.find_element(By.XPATH, '/html/body/div/div/div[2]/form/div[1]/div[14]/div[2]/div/input').click()
time.sleep(0.3)
driver.find_element(By.XPATH, '/html/body/div/div/div[2]/form/div[1]/div[16]/div/div[2]/div[1]/ul/li[3]').click()
time.sleep(0.3)
driver.find_element(By.XPATH, '/html/body/div/div/div[2]/form/div[1]/div[16]/div/div[1]/button[2]').click()
time.sleep(0.3)
driver.find_element(By.XPATH, '/html/body/div/div/div[2]/form/div[1]/div[17]/div[2]/div/input').click()
time.sleep(0.3)
driver.find_element(By.XPATH, '/html/body/div/div/div[2]/form/div[1]/div[19]/div/div[2]/div[1]/ul/li[2]').click()
time.sleep(0.3)
driver.find_element(By.XPATH, '/html/body/div/div/div[2]/form/div[1]/div[19]/div/div[1]/button[2]').click()
time.sleep(0.3)
driver.find_element(By.XPATH, '/html/body/div/div/div[2]/form/div[1]/div[20]/div[2]/div/input').click()
time.sleep(0.3)
driver.find_element(By.XPATH, '/html/body/div/div/div[2]/form/div[1]/div[22]/div/div[2]/div[1]/ul/li[3]').click()
time.sleep(0.3)
driver.find_element(By.XPATH, '/html/body/div/div/div[2]/form/div[1]/div[22]/div/div[1]/button[2]').click()
time.sleep(0.3)
driver.find_element(By.XPATH, '/html/body/div/div/div[2]/form/div[1]/div[23]/div[2]/div/input').click()
time.sleep(0.3)
driver.find_element(By.XPATH, '/html/body/div/div/div[2]/form/div[1]/div[25]/div/div[2]/div[1]/ul/li[3]').click()
time.sleep(0.3)
driver.find_element(By.XPATH, '/html/body/div/div/div[2]/form/div[1]/div[25]/div/div[1]/button[2]').click()
time.sleep(0.3)
driver.find_element(By.XPATH, '/html/body/div/div/div[2]/form/div[1]/div[26]/div[2]/div/input').click()
time.sleep(0.3)
driver.find_element(By.XPATH, '/html/body/div/div/div[2]/form/div[1]/div[28]/div/div[2]/div[1]/ul/li[2]').click()
time.sleep(0.3)
driver.find_element(By.XPATH, '/html/body/div/div/div[2]/form/div[1]/div[28]/div/div[1]/button[2]').click()
time.sleep(0.3)
driver.find_element(By.XPATH, '/html/body/div/div/div[2]/form/div[2]/button').click()
# driver.find_element(By.XPATH, '/html/body/div/div/div[2]/form/div[2]/button/div/span').click()
# time.sleep(0.3)
# driver.find_element(By.XPATH, '/html/body/div/div/div[2]/form/div[2]/button/div').click()

time.sleep(20)
